config/routes.rb
Xmaslist::Application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :sessions

  resources :users do
    resources :gifts
  end

  get 'users/:user_id/gifts/:id/purchase' => 'gifts#purchase', as: :purchase_user_gift
  get 'users/:user_id/gifts/:id/return'   => 'gifts#return',   as: :return_user_gift

  get 'login'  => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'boomtown' => 'boomtown#boomtown'

  root to: 'users#index'
end

app/models/gift.rb
class Gift < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :name, presence: true
  validates :url,  presence: true

  def sell!(user)
    self.purchased_by_user_id = user.id unless self.user == user
    save
  end

  def return!
    self.purchased_by_user_id = nil
    save
  end

  def purchased?
    !self.purchased_by_user_id.nil?
  end

  def purchased_by?(user)
    self.purchased_by_user_id == user.id
  end

  def purchaser
    begin
      User.find(self.purchased_by_user_id)
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end
end

app/models/gift_notifier.rb
class GiftNotifier
  attr_reader :user_id, :gift_id

  def initialize(user_id, gift_id)
    @user_id = user_id
    @gift_id = gift_id
  end

  def send_notifications
    User.with_email_notifications.where(
      "id <> ?", user_id
    ).each do |to|
      email = GiftMailer.gift_added_notification(user, to, gift)
      email.deliver if email
    end
  end

  private

  def user
    @user ||= User.find(user_id)
  end

  def gift
    @gift ||= Gift.find(gift_id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :gifts

  validates :name,     presence: true
  validates :email,    presence: true, uniqueness: true
  validates :password, presence: true

  scope :with_email_notifications, -> { where email_notifications: true }

  def purchase(gift)
    gift.sell!(self)
  end

  def return(gift)
    purchased_by = gift.purchased_by?(self)
    gift.return! if purchased_by
    return purchased_by
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate
    redirect_to login_path, notice: 'Please login to continue.' unless current_user
  end
end

app/controllers/boomtown_controller.rb
class BoomtownController < ActionController::Base
  BoomtownException = Class.new(StandardError)

  def boomtown
    raise BoomtownException.new 'BOOOOOM!'
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_filter :authenticate

  def index
    user = User.find(params[:user_id])
    @gifts = Gift.where('user_id = ?', user.id).order(:name)
    flash.now[:warning] = "#{user.name} has not added any gifts" if @gifts.empty?
  end

  def new
    begin
      @user = User.find(params[:user_id])
      @gift = @user.gifts.build
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path
    end
  end

  def create
    @user = User.find(params[:user_id])
    @gift = @user.gifts.build(gift_params)
    if @gift.save
      send_notifications_for(@user, @gift)
      redirect_to user_gifts_path(@user), notice: 'Your gift has been added!'
    else
      flash.now[:error] = 'Both name and url are required!'
      render 'new'
    end
  end

  def edit
    begin
      @gift = Gift.find(params[:id])
      @user = User.find(params[:user_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path
    end
  end

  def update
    @gift = Gift.find(params[:id])
    @user = User.find(params[:user_id])
    if current_user == @user && @gift.update_attributes(gift_params)
      redirect_to user_gifts_path(@gift.user), notice: 'Your gift has been updated!'
    else
      flash.now[:error] = 'Both name and url are required!'
      render 'edit'
    end
  end

  def destroy
    begin
      @user = User.find(params[:user_id])
      Gift.find(params[:id]).destroy
      redirect_to user_gifts_path(@user), notice: 'Your gift has been deleted!'
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path
    end
  end

  def purchase
    begin
      @user = User.find(params[:user_id])
      @gift = Gift.find(params[:id])
      current_user.purchase(@gift)
      redirect_to user_gifts_path(@user), notice: 'Gift has been marked as purchased!'
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path
    end
  end

  def return
    begin
      @user = User.find(params[:user_id])
      @gift = Gift.find(params[:id])
      if current_user.return(@gift)
        flash[:notice] = 'Gift is no longer marked as purchased!'
      else
        flash[:error] = 'Sorry. You cannot unmark gifts that you did not purchase!'
      end
      redirect_to user_gifts_path(@user)
    rescue ActiveRecord::RecordNotFound
      redirect_to users_path
    end
  end

  private

  def send_notifications_for(user, gift)
    GiftNotifierWorker.perform_async user.id, gift.id
  end

  def gift_params
    params.require(:gift).permit(:name, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_gifts_path(user),
        notice: "Hello #{user.name}! You are now logged in."
    else
      flash.now[:error] = "Sorry! Invalid email or password."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "You are now logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, only: [:index, :edit, :update]

  def index
    @users = User.order(:name)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.email = @user.email.try(:downcase)
    if @user.save
      redirect_to login_path, notice: "Account created! You may now login."
    else
      flash.now[:error] = "Sorry! There were errors creating your account."
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes user_params
      redirect_to user_gifts_path(@user),
        notice: "Your account details have been updated!"
    else
      flash.now[:error] = "Sorry! There were errors updating your account."
      render 'edit'
    end
  end

  private

  def user_params
    @user_params ||= begin
      params.require(:user).permit([
        :email,
        :email_notifications,
        :name,
        :password,
        :password_confirmation
      ]).tap do |params|
        params[:email] = params[:email].to_s.downcase
        params[:password_confirmation] ||= params[:password]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gifts/_form.html.haml
= form_for([@user, @gift]) do |f|
  .labels
    = f.label :name
    = f.label :url
  .fields
    = f.text_field :name
    = f.text_field :url
  = f.submit submit_label, class: 'submit'

app/views/gifts/edit.html.haml
= render partial: 'form', locals: { submit_label: 'Save Gift' }

app/views/gifts/index.html.haml
%ul#gifts
  - @gifts.each do |gift|
    %li.gift
      - if current_user == gift.user
        .actions
          = link_to 'Edit',
              edit_user_gift_path(user_id: gift.user, id: gift),
              class: 'edit'
          = link_to 'Delete',
              user_gift_path(user_id: gift.user, id: gift),
              method: :delete,
              class: 'delete'
      - else
        .actions
          - if gift.purchased?
            = link_to 'Unmark as Purchased',
                return_user_gift_path(user_id: gift.user, id: gift),
                title: 'Un-mark this gift as purchased',
                class: 'return'
          - else
            = link_to 'Mark as Purchased',
                purchase_user_gift_path(user_id: gift.user, id: gift),
                title: 'Mark this gift as purchased',
                class: 'purchase'
      = link_to gift.name, gift.url, target: 'blank'

app/views/gifts/new.html.haml
= render partial: 'form', locals: { submit_label: 'Add Gift' }

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= 'Christmas List'
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #container
      #header
        %ul#navigation
          - if current_user
            %li{title: 'View all gift lists'}
              = link_to 'All Lists', users_path
            %li{title: 'View your gift list'}
              = link_to 'My List', user_gifts_path(current_user)
            %li{title: 'Add a gift to your gift list'}
              = link_to 'Add Gift', new_user_gift_path(current_user)
        #current-user
          - if current_user
            = "Logged in as "
            %span= link_to current_user.name, edit_user_path(current_user)
            = link_to 'Logout', logout_path
          - else
            = link_to 'Login', login_path
            = link_to 'Create Account', new_user_path
      #content
        - if flash
          %ul#flash-messages
            - flash.each do |type, message|
              %li{class: "flash #{type}"}= message
        = yield
      #snowman
        = image_tag 'snowman.png'

app/views/users/_form.html.haml
= form_for @user do |f|
  .labels
    = f.label :name
    = f.label :email
    = f.label :password
    = f.label :email_notifications
  .fields
    = f.text_field :name
    = f.text_field :email
    = f.password_field :password
    = f.check_box :email_notifications
  = f.submit submit_text, class: 'submit'

app/views/users/_validations.html.haml
- if @user.errors.size > 0
  %ul#validation-messages
    - @user.errors.full_messages.reject { |m| m.include? 'digest' }.each do |m|
      %li= m

app/views/users/edit.html.haml
= render partial: 'validations'
= render partial: 'form', locals: { submit_text: 'Update Account' }

app/views/users/index.html.haml
%ul#users
  - @users.each do |user|
    %li.user= link_to user.name, user_gifts_path(user)

app/views/users/new.html.haml
= render partial: 'validations'
= render partial: 'form', locals: { submit_text: 'Create Account' }